import {
  Geist,
  Geist_Mono,
  Delius_Swash_Caps,
  Caveat,
  Gwendolyn,
  Merienda,
  Rancho,
  Markazi_Text,
  Tinos,
  Pirata_One,
  Condiment,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const deliusSwashCaps = Delius_Swash_Caps({
  variable: "--font-delius-swash-caps",
  weight: "400",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  weight: "400",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gwendolyn = Gwendolyn({
  variable: "--font-gwendolyn",
  weight: "700",
  subsets: ["latin"],
});

const rancho = Rancho({
  variable: "--font-rancho",
  weight: "400",
  subsets: ["latin"],
});

const condiment = Condiment({
  variable: "--font-condiment",
  weight: "400",
  subsets: ["latin"],
});

const markaziText = Markazi_Text({
  variable: "--font-markazi-text",
  weight: "400",
  subsets: ["latin"],
});

const tinos = Tinos({
  variable: "--font-tinos",
  weight: "400",
  subsets: ["latin"],
});

const pirataOne = Pirata_One({
  variable: "--font-pirata-one",
  weight: "400",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main
          className={`${geistSans.variable} ${geistMono.variable} ${deliusSwashCaps.variable} ${caveat.variable} ${gwendolyn.variable} ${merienda.variable} ${rancho.variable} ${markaziText.variable} ${tinos.variable} ${pirataOne.variable} ${condiment.variable}`}
        >
          {children}{" "}
        </main>
      </body>
    </html>
  );
}
